### ISSUE TITLE
Drop box changes do not trigger Unsaved Changes warning when leaving the page

### ISSUE THREAD

**Issue by arpost** [eurekaclinical/eurekaclinical-analytics-webclient#20]
When populating input fields in the Cohorts and Phenotypes pages, clicking the Cancel button or clicking the menu items at the top of the page trigger an Unsaved Changes warning dialog. This does not happen if the user puts items in a multi or single drop box and does not populate any regular input fields, as if the page does not detect that changes were made.

**Comment by jsons** [comment]
@arpost  this issue has been corrected in this PR:
https://github.com/eurekaclinical/eurekaclinical-analytics-webclient/pull/21

**Comment by arpost** [comment]
Thanks.
