### ISSUE TITLE
Error when deleting Drop Zone items

### ISSUE THREAD

**Issue by jsons** [eurekaclinical/eurekaclinical-analytics-webclient#8]
Noticed when deleting drop zone items this error is displayed:  TypeError: vm.keys.split is not a function at tree-multi-drop-zone-ctrl.js:66.  Will need to address this issue

**Comment by arpost** [comment]
vm.keys is only defined when the drop zone is created with a pre-existing list of items. So, we need to check if it is defined before using it. Also, split is incorrect -- the function name we're looking for is splice.
